// mobile/app/search.tsx
import React from "react";
import { View, Text, Image, TextInput, ScrollView, TouchableOpacity } from "react-native";
import { ArrowLeft, SlidersHorizontal, Search, Star } from "lucide-react-native";

import { router } from "expo-router";

const SearchScreen = () => {
  return (
    <ScrollView style={{ flex: 1, backgroundColor: "black", paddingBottom: 40 }} contentContainerStyle={{ paddingHorizontal: 20, paddingTop: 70 }}>
      <View style={{ position: "absolute", top: 0, left: 0, right: 0, padding: 16, backgroundColor: "black", zIndex: 10 }}>
        <View style={{ flexDirection: "row", justifyContent: "space-between", alignItems: "center" }}>
          <TouchableOpacity style={{ flexDirection: "row", alignItems: "center", position: "relative" }} onPress={() => router.back()}>
            <ArrowLeft color="white" />
            <Text style={{ fontSize: 15, fontWeight: "bold", color: "white", opacity: 0.7, left: 30, position: "absolute" }}>Kembali</Text>
          </TouchableOpacity>
          <Text style={{ fontSize: 20, fontWeight: "bold", color: "white" }}>Search</Text>
          <SlidersHorizontal color="white" />
        </View>

        <View style={{ position: "relative", marginTop: 20 }}>
          <Search color="white" style={{ position: "absolute", left: 12, top: 12 }} />
          <TextInput
            placeholder="Attack On Titan"
            placeholderTextColor="gray"
            aria-hidden={true}
            onKeyPress={(e) => {
              if ((e as unknown as KeyboardEvent).key === "Enter" || (e as unknown as KeyboardEvent).key === "enter") {
                console.log("Mulai mencari data...")
              }
            }}
            style={{ backgroundColor: "#1e1e1e", borderRadius: 16, paddingLeft: 48, color: "white", height: 48, borderColor: "#ffffff10", borderWidth: 1 }}
          />
        </View>
      </View>

      <View style={{ marginTop: 60 }}>
        <Text style={{ fontSize: 24, fontWeight: "600", color: "white", marginBottom: 16 }}>Relevan result</Text>

        <View>
          <Image source={require("@/assets/images/konosuba.jpg")} style={{ height: 200, width: "100%", borderRadius: 16 }} resizeMode="cover" />
          <View style={{ marginTop: 12 }}>
            <Text style={{ fontSize: 18, fontWeight: "600", color: "white" }}>KonoSuba: God's Blessing on This Wonderful World! 3</Text>
            <View style={{ flexDirection: "row", alignItems: "center", marginVertical: 8 }}>
              <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: "#facc15" }} />
              <Text style={{ color: "white", opacity: 0.8, marginLeft: 6 }}>On Going</Text>
              <View style={{ flexDirection: "row", alignItems: "center", marginLeft: "auto" }}>
                <Text style={{ color: "white", opacity: 0.8 }}>2020</Text>
                <View style={{ flexDirection: "row", alignItems: "center", marginLeft: 20 }}>
                  <Star color="white" size={16} />
                  <Text style={{ color: "#22c55e", marginLeft: 4 }}>4.4</Text>
                </View>
              </View>
            </View>
            <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexDirection: "row" }}>
              {["Comedy", "Isekai", "Romance", "Ecchi"].map((tag, idx) => (
                <Text key={idx} style={{ color: "#ef4444", marginRight: 12 }}>{tag}</Text>
              ))}
            </ScrollView>
          </View>
        </View>

        {[1, 2, 3, 4, 5, 6, 7, 8, 9, 10].map((item, idx) => (
          <View key={idx} style={{ flexDirection: "row", gap: 12, marginTop: 24 }}>
            <Image
              source={require("@/assets/images/arona.jpg")}
              style={{ width: 90, height: 140, borderRadius: 16 }}
              resizeMode="cover"
            />
            <View style={{ flex: 1, justifyContent: "center" }}>
              <Text style={{ fontSize: 18, fontWeight: "600", color: "white" }}>
                {item % 2 === 0 ? "Blue Archive: Anime Terkeren Sedunia" : "Attack On Titan: Ngantuks"}
              </Text>
              <View style={{ flexDirection: "row", alignItems: "center", marginVertical: 6 }}>
                <View style={{ width: 10, height: 10, borderRadius: 5, backgroundColor: "#22c55e" }} />
                <Text style={{ color: "white", opacity: 0.8, marginLeft: 6 }}>Finish</Text>
              </View>
              <View style={{ flexDirection: "row", alignItems: "center" }}>
                <Text style={{ color: "white", opacity: 0.8 }}>2023</Text>
                <View style={{ flexDirection: "row", alignItems: "center", marginLeft: 20 }}>
                  <Star color="white" size={16} />
                  <Text style={{ color: "#22c55e", marginLeft: 4 }}>4.7</Text>
                </View>
              </View>
              <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{ flexDirection: "row", marginTop: 12 }}>
                {[...Array((item % 2 === 0 ? 8 : 2)).fill(item % 2 === 0 ? "Romance" : "Action")].map((tag, idx) => (
                  <Text key={idx} style={{ color: "#ef4444", marginRight: 12 }}>{tag}</Text>
                ))}
              </ScrollView>
            </View>
          </View>
        ))}
      </View>
    </ScrollView>
  );
};

export default SearchScreen;

// frontend/src/lib/components/mobile/Search.svelte
<script lang="ts">
  import { ArrowLeft, SlidersHorizontal, Search, Star } from "@lucide/svelte";
  import { scale } from "svelte/transition";
</script>

<div class="pt-15 text-white px-5 pb-[70px]" in:scale={{ duration: 200, start: 0.95 }}>
  <div class="!fixed z-10 w-full block h-auto bg-black left-0 top-0 p-4">
    <div class="flex justify-between w-full items-center h-auto">
      <button on:click={() => window.history.back()}>
        <ArrowLeft />
      </button>
      <h1 class="text-[20px] font-bold">Search</h1>
      <SlidersHorizontal />
    </div>
    <div class="relative mt-5">
      <Search class="absolute left-3 top-0 bottom-0 my-auto" />
      <input
        class="bg-dark outline-none pl-12 w-full h-auto p-2 rounded-2xl border border-white/10"
        type="text"
        placeholder="Attack On Titan"
      />
    </div>
  </div>

  <div class="mt-17">
    <h1 class="text-title-large font-semibold mb-5 opacity-70">Relevan result</h1>
    <div class="w-full">
      <img
        class="rounded-2xl h-[200px] w-full object-cover"
        src="/images/konosuba.jpg"
        alt="Konosuba"
      />
      <div class="mt-3 flex flex-col justify-between">
        <h1 class="text-title-medium font-semibold">
          KonoSuba: God's Blessing on This Wonderful World! 3
        </h1>
        <div class="flex gap-2 items-center my-2">
          <span class="block w-[10px] h-[10px] bg-yellow-500 rounded-full"
          ></span>
          <h1 class="opacity-80 text-label-small">On Going</h1>
          <div class="flex gap-5 ml-auto items-center text-label-small">
            <h1 class="opacity-80">2020</h1>
            <div class="flex gap-2 items-center">
              <Star size="15" fill="green" color="green" />
              <h1 class="opacity-80 text-green-500">4.4</h1>
            </div>
          </div>
        </div>
        <div class="flex flex-nowrap items-center text-label-small overflow-x-auto gap-3">
          <span class="text-red-500">Comedy</span>
          <span class="text-red-500">Isekai</span>
          <span class="text-red-500">Romance</span>
          <span class="text-red-500">Ecchi</span>
        </div>
      </div>
    </div>
    <ul class="mt-7">
      <li class="mt-5">
        <div class="w-full grid grid-cols-[90px_1fr] gap-3 justify-start">
          <img
            class="rounded-2xl shrink-0 h-[140px] w-[90px] object-cover"
            src="/images/arona.jpg"
            alt="Konosuba"
          />
          <div class="flex w-full min-w-0 flex-col justify-center">
            <h1 class="text-title-medium font-semibold">
              Blue Archive: Anime Terkeren Sedunia
            </h1>
            <div class="flex gap-2 items-center my-2">
              <span class="block w-[10px] h-[10px] bg-green-500 rounded-full"
              ></span>
              <h1 class="opacity-80 text-label-small">Finish</h1>
            </div>
            <div class="flex gap-5 items-center text-label-small">
              <h1 class="opacity-80">2023</h1>
              <div class="flex gap-2 items-center">
                <Star size="15" fill="green" color="green" />
                <h1 class="opacity-80 text-green-500 text-label-small">4.7</h1>
              </div>
            </div>
            <div class="flex flex-nowrap text-label-small no-scroll items-center w-full mt-3 overflow-x-auto gap-3">
              <span class="text-red-500">Comedy</span>
              <span class="text-red-500">Isekai</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
            </div>
          </div>
        </div>
      </li>
      
      <li class="mt-5">
        <div class="w-full grid grid-cols-[90px_1fr] gap-3 justify-start">
          <img
            class="rounded-2xl shrink-0 h-[140px] w-[90px] object-cover"
            src="/images/arona.jpg"
            alt="Konosuba"
          />
          <div class="flex w-full min-w-0 flex-col justify-center">
            <h1 class="text-title-medium font-semibold">
              Blue Archive: Anime Terkeren Sedunia
            </h1>
            <div class="flex gap-2 items-center my-2">
              <span class="block w-[10px] h-[10px] bg-green-500 rounded-full"
              ></span>
              <h1 class="opacity-80 text-label-small">Finish</h1>
            </div>
            <div class="flex gap-5 items-center text-label-small">
              <h1 class="opacity-80">2023</h1>
              <div class="flex gap-2 items-center">
                <Star size="15" fill="green" color="green" />
                <h1 class="opacity-80 text-green-500 text-label-small">4.7</h1>
              </div>
            </div>
            <div class="flex flex-nowrap text-label-small no-scroll items-center w-full mt-3 overflow-x-auto gap-3">
              <span class="text-red-500">Comedy</span>
              <span class="text-red-500">Isekai</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
            </div>
          </div>
        </div>
      </li>
      
      <li class="mt-5">
        <div class="w-full grid grid-cols-[90px_1fr] gap-3 justify-start">
          <img
            class="rounded-2xl shrink-0 h-[140px] w-[90px] object-cover"
            src="/images/arona.jpg"
            alt="Konosuba"
          />
          <div class="flex w-full min-w-0 flex-col justify-center">
            <h1 class="text-title-medium font-semibold">
              Blue Archive: Anime Terkeren Sedunia
            </h1>
            <div class="flex gap-2 items-center my-2">
              <span class="block w-[10px] h-[10px] bg-green-500 rounded-full"
              ></span>
              <h1 class="opacity-80 text-label-small">Finish</h1>
            </div>
            <div class="flex gap-5 items-center text-label-small">
              <h1 class="opacity-80">2023</h1>
              <div class="flex gap-2 items-center">
                <Star size="15" fill="green" color="green" />
                <h1 class="opacity-80 text-green-500 text-label-small">4.7</h1>
              </div>
            </div>
            <div class="flex flex-nowrap text-label-small no-scroll items-center w-full mt-3 overflow-x-auto gap-3">
              <span class="text-red-500">Comedy</span>
              <span class="text-red-500">Isekai</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
            </div>
          </div>
        </div>
      </li>

      <li class="mt-5">
        <div class="w-full grid grid-cols-[90px_1fr] gap-3 justify-start">
          <img
            class="rounded-2xl shrink-0 h-[140px] w-[90px] object-cover"
            src="/images/arona.jpg"
            alt="Konosuba"
          />
          <div class="flex w-full min-w-0 flex-col justify-center">
            <h1 class="text-title-medium font-semibold">
              Blue Archive: Anime Terkeren Sedunia
            </h1>
            <div class="flex gap-2 items-center my-2">
              <span class="block w-[10px] h-[10px] bg-green-500 rounded-full"
              ></span>
              <h1 class="opacity-80 text-label-small">Finish</h1>
            </div>
            <div class="flex gap-5 items-center text-label-small">
              <h1 class="opacity-80">2023</h1>
              <div class="flex gap-2 items-center">
                <Star size="15" fill="green" color="green" />
                <h1 class="opacity-80 text-green-500 text-label-small">4.7</h1>
              </div>
            </div>
            <div class="flex flex-nowrap text-label-small no-scroll items-center w-full mt-3 overflow-x-auto gap-3">
              <span class="text-red-500">Comedy</span>
              <span class="text-red-500">Isekai</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
            </div>
          </div>
        </div>
      </li>

      <li class="mt-5">
        <div class="w-full grid grid-cols-[90px_1fr] gap-3 justify-start">
          <img
            class="rounded-2xl shrink-0 h-[140px] w-[90px] object-cover"
            src="/images/arona.jpg"
            alt="Konosuba"
          />
          <div class="flex w-full min-w-0 flex-col justify-center">
            <h1 class="text-title-medium font-semibold">
              Blue Archive: Anime Terkeren Sedunia
            </h1>
            <div class="flex gap-2 items-center my-2">
              <span class="block w-[10px] h-[10px] bg-green-500 rounded-full"
              ></span>
              <h1 class="opacity-80 text-label-small">Finish</h1>
            </div>
            <div class="flex gap-5 items-center text-label-small">
              <h1 class="opacity-80">2023</h1>
              <div class="flex gap-2 items-center">
                <Star size="15" fill="green" color="green" />
                <h1 class="opacity-80 text-green-500 text-label-small">4.7</h1>
              </div>
            </div>
            <div class="flex flex-nowrap text-label-small no-scroll items-center w-full mt-3 overflow-x-auto gap-3">
              <span class="text-red-500">Comedy</span>
              <span class="text-red-500">Isekai</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
              <span class="text-red-500">Romance</span>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>
